### ISSUE TITLE
Crash due to no appropriate "Current time of day" video existing

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#101]
**Describe the bug**
A blank screen which eventually freezes the screensaver and crashes the whole application, if not forced closed, is displayd when the "Prioritize current time of day" option is checked, but there is no video that matches that condition.

**To Reproduce**
1. Go to Settings
2. Enable "Prioritize current time of day"
3. Preview screensaver or wait for it to start
4. Observe the issue

**Expected behavior**
Select a random video and don't crash or freeze. To be noted, the suggested behavior seemed to exist on older versions of Aerial.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/65589110/194632753-be8b0d93-4138-4f04-b974-8bf636b095ba.png)

**Aerial Version**
Aerial v1.0.0

**Comment by OrangeJedi** [comment]
I was able to reproduce this error. Thanks @VasilisPat for all the stress testing on v1.0.0 BTW. 
I think it might have something to do with an update made to the .json file when adding the new videos. I'll take a look and see if that's the case.

On a side note, not ever video (most of them?) had a `day` or `night` tag added to it. This could be a project someone could do in the future.

**Comment by VasilisPat** [comment]
I might be able to help edit the json file containing the videos. Is there any other time of day option except day/night? Also any suggestion on which default tag to attach to underwater and space videos, in order for them to work as well?

**Comment by OrangeJedi** [comment]
Yeah, those are some good questions. It's easy to add another option other than `day `or `night `, but should we? What are the space videos? Does every video need day or night tag? I'll open another issue for this so we can make a plan that will make the most sense. 

Otherwise, I found the issue causing the day/night code to break. It wasn't in the json as I though, but in the video picking code. It's been added to the v1.0.1 branch.
