### ISSUE TITLE
4K Video Toggle

### ISSUE THREAD

**Issue by gordoncasey** [OrangeJedi/Aerial#111]
Love what you've done; is it possible to get an option to have the 4K videos downloaded/stored as well?

**Comment by OrangeJedi** [comment]
Not as of right now. See #17. Apple releases the 4K videos only in the h.256 format and currently Aerial cannot play any h.265 videos due to its framework and licensing restrictions. If you or anyone else has any thoughts how how Aerial can play these h.256 videos I would love to try and implement them.
