### ISSUE TITLE
Show text on specific monitor.

### ISSUE THREAD

**Issue by Alexyoe** [OrangeJedi/Aerial#112]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to show text on only one monitor.

**Describe the solution you'd like**
An option in text settings to choose which monitor text will appear on.

**Comment by OrangeJedi** [comment]
This is a brilliant idea! I'd love to add it as a feature in Aerial. I'm still working out what features I will be working on for the next release and I will certainly consider this. Thank you so much for the great suggestion!

It will be a bit tricky to code because as of right now each screen has no way to differentiate itself from each other, but the groundwork to add is already in the program.

**Comment by OrangeJedi** [comment]
Added in v1.2.0. Each text line has a drop down you can use to select which monitor it appears on. Note, the selector only appears on systems with 2 or more screens.
