### ISSUE TITLE
Deformed video on special size screen

### ISSUE THREAD

**Issue by Jitrixis** [OrangeJedi/Aerial#119]
**Describe the bug**
When using aerial on a 32:9 screen and on a rotated screen, the video is deformed and stretched.

**To Reproduce**
Test on a 32:9 screen or rotate a screen to portrait mode

**Expected behavior**
being beautifull

**Screenshots**
Video is streched

**Aerial Version**
What version of Aerial are you running?
1.1.0

**Additional context**

**Comment by OrangeJedi** [comment]
This is a problem we've tried to deal with before. (see #30 & #72)

Right now you can have Aerial "crop and zoom" rather than fill if you check the `disable all video processing` box under the style tab. Let me know if that is what you are looking for. 

The app should replicated that behavior with video processing on, I'll dive deeper into it when I have time.

**Comment by OrangeJedi** [comment]
After way too many tried to fix this, I think v1.2.0 landed on a good solution. The update has a fix where you can choose between the old stretch option, and a crop option which will maintain the video scale and crop it in the center.
