### ISSUE TITLE
Lock Screen timeout puts computer to sleep when Aerial is running

### ISSUE THREAD

**Issue by maggle-swim** [OrangeJedi/Aerial#145]
**Describe the bug**

When "Lock the computer after running" is ticked - the screensaver will only be active for about 5 minutes - which the sleep timer for the computer when the lock screen is active. 

**To Reproduce**
1. Go to Settings
2. Click on Lock the computer after running
3. start screensaver, and wait 5 minutes after lock screen activates 

**Expected behavior**

computer should run based on expected blank screen and sleep timers set on app or within power plan 

**Screenshots**

**Aerial Version**
What version of Aerial are you running?
1.2.0
**Additional context**

Idea for fix would be to disable lock screen timeout when screensaver is active and restore to original value when screensaver is deactivated

**Comment by maggle-swim** [comment]
trying the .scr fix from #141 didn't notice any stuttering yet

**Comment by OrangeJedi** [comment]
Yep, it sounds like your Windows power management is set to lock your computer before Aerial finished running. Unfortunately having Aerial change those settings it not something the app has assess to do right now, or in the foreseeable future due to app permissions. However, perhaps a warning could be displayed? I will add this to the list for future updates.
