### ISSUE TITLE
Vertical (portrait) causes bad proportions

### ISSUE THREAD

**Issue by natmil** [OrangeJedi/Aerial#30]
Hey!

I think there should be the option to choose a fit. Specially for vertical resolutions.

![screen2](https://user-images.githubusercontent.com/18117559/82149434-1a5b7700-9857-11ea-8580-5e6ea7db9521.jpg)

**Comment by OrangeJedi** [comment]
I see your problem. As you can see I hadn't really thought of vertical screens displaying the video. 
It's kind of hard because the video aren't vertical themselves and it not super clear how you would want them to display. I would like to add "fill, fit, stretch, etc." options though I don't know how much it will help. 
I'll post an update here when I make some progress. In the meantime you can configure Aerial to run only of one screen. Unchecking the "Disable video processing" could also change what your seeing on the vertical screen.

**Comment by rossnick** [comment]
I'll add here, it's the same thing on 21:9 screen. My main screen is 21:9 (3440x1440) and the video is streched...

**Comment by jonathanmwood** [comment]
I'll second wanting the 21:9 support. Would love to be able to fill the screen with the videos at the correct aspect ratio on my ultrawide.

**Comment by Ivan0xFF** [comment]
The Mac version fills instead of stretching. I use a vertical screen and an ultrawide monitor so this issue was immediately apparent when I switched from my MacBook to my gaming PC on my screens.
