### ISSUE TITLE
Video Playback Duplicate

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#38]
**Describe the bug**
Sometimes, although rarely, when the screensaver automatically starts, both screens play the same video. I have noticed it only twice. Play same video on both screens is disabled. After the first video, different ones play at each screen.

**Aerial Version**
Beta 0.5.3

**Additional context**
Also another "bug", the order of the videos is a little bit predifined. Although which video starts playing when the screensaver starts is different, the combination of which plays in each monitor is almost identical(ex. Downtown with Great Wall 3 always play alongside).

**Comment by OrangeJedi** [comment]
The videos for both screens are randomly chosen independent of each other. This mean that while more often than not two screens will play different videos, it is possible that the same video will be chosen on both screens. 
As to the same videos playing side by side, each screen is an separate process that independently (and randomly) selects a video to play. Again, it is possible for the same "pair" of videos to play together often, but this is just random chance.
Neither of these are really bug that are worth fixing. You can always use the right arrow key to change the videos for both screens.

*As an aside, there were problems with Aerial random video selection because it was possible to get the same video twice in a row, or rather frequently  so the "Avoid Duplicate Videos" option was added which prevents Aerial from playing the last few videos (40% of the total number).*
