### ISSUE TITLE
Video Quality?

### ISSUE THREAD

**Issue by 6illess** [OrangeJedi/Aerial#47]
Is it possible to choose the quality of the video's? I noticed they are downloaded in 1080p, however I prefer the 4K versions. Can I manually download and replace them by using the same file names?

**Comment by VasilisPat** [comment]
As mentioned in #17, due to the framework of the app, 4K videos are not supported at the moment. However there is a solution explained by the develloper [here](https:/github.com/OrangeJedi/Aerial/issues/17#issuecomment-611049055). 

If the solution covers your case, feel free to close the issue. If something doesn't work as intended we are here to help!

**Comment by 6illess** [comment]
Thanks, sorry for opening a duplicate Issue.
