### ISSUE TITLE
Click Preview shows Aerial clock but videos don't show on screen

### ISSUE THREAD

**Issue by prediscover** [OrangeJedi/Aerial#5]
Thanks for the 0.4.0 beta today. Installed using the Zip File and when clicking preview, only the clock text appears, no video. 

I did have the original Aerial by cDima installed, I deleted it from the c:\Windows folder.

**Comment by OrangeJedi** [comment]
Hey, glad to hear you appreciated v0.4.0!
A couple of questions:

1. Did you have a previous version installed, and if so, did the video play then?
2. In the 'settings' menu under the video tab when you click on a video does it play?
3. You may need to install Apple's Root Certificate from  https://www.apple.com/certificateauthority/ to play the videos. I'm working on fixing this for v0.5.0, but basically Apple self-signed the web certificate for the videos and you may need to install the certificate so your computer recognized the URL as valid.

**Comment by prediscover** [comment]
1. I did not have a previous version installed.
2. No, when I click on a video, it does not play. 

that probably means I need the certificate huh.

**Comment by OrangeJedi** [comment]
Yeah. I was doing some testing today on another computer and was running into the same issue. The issue will be fixed in v0.5.0 though. You can either install the certificate or wait for for v0.5.0.
Or...
You could into the Aerial folder and find app.js `aerial-0.4.0\resources\app\app.js` and open it up in a text editor (notepad works fine) and add the following lines of code at the end.
```
app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
    if (url.match(/^https:\/\/sylvan.apple.com/) !== null) {
        event.preventDefault();
        callback(true)
    } else {
        callback(false)
    }
});
```
This should get around needing the certificate to view the videos.
Let me know if you have any issues.

**Comment by freddy1407** [comment]
Same on that issue :/
certificate already installed.
no videos loading on any version.
using Windows 10, with Firefox downloaded. tested Zip and scr.

Thanks so much!

**Comment by OrangeJedi** [comment]
Are the videos loading in the video tab of the config menu? I've also noticed that sometimes it takes a few seconds for the videos to load, though I'm going to assume that you that isn't your issue. When you click the preview button on the screensaver selector can you see a window open on your task bar, or if configured, text pop up?

**Comment by jnlx** [comment]
I had the same issue, no video at all, just an icon in the taskbar, even after instaling the certificate.
i added the lines of code as told by OrangeJedi and now it works fine.
Thank you OrangeJedi, i was hoping for sometimes now that someone would take on this project, since i am useless for coding ;-)

Keep on the good work, Thank you :D

**Comment by Aleatoire** [comment]
Same, i just get the clock :/
One little things, if in the settings you could add a enable/disable mutli-screen would be nice 👍 
Thanks :)

**Comment by OrangeJedi** [comment]
This is now fixed in [v0.5.0](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.0-beta). Aerial no longer needs Apple's cert. If you are still having problems with videos playing after v0.5.0 please create a new issue.

**Comment by Aleatoire** [comment]
Hello, i've tested.
It's not working every time.
And this error is showing up.
![Error](https://user-images.githubusercontent.com/3025616/78643667-e46cbf80-78b4-11ea-930f-fd73c9d3952a.jpg)

**Comment by freddy1407** [comment]
Same Error here!

**Comment by OrangeJedi** [comment]
I put this in #12, I'll put it here too.
> 
> 
> I think I fixed it. Download and install [v0.5.1](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.1-beta), it shouldn't throw an error. Thanks for bringing this to my attention, let me know if you continue to have problems.

**Comment by prediscover** [comment]
I can confirm. Having originally the 0.4.0 beta, upgrading directly to 0.5.1 fixes the issue or the video displaying. Thanks! @OrangeJedi
