### ISSUE TITLE
Monitor wont go to sleep

### ISSUE THREAD

**Issue by FotisSp** [OrangeJedi/Aerial#51]
Hello and big thanks for your great work so far. 

I am experiencing the issue that the monitor wont go to sleep while the screen saver plays. Although i have setted it up as to go to sleep after 15 minutes nothing happens.  

Has anyone else experienced the same issue ? Has anyone find and solution to this ? 

**Aerial Version**
0.5.3

**Comment by VasilisPat** [comment]
Hi there,

I have noticed the same issue appears on my pc when all the settings are correctly set. I assume that as in my case, your screensaver start time is set before the sleep time. 
I did a quick google search on this issue and it appears that this is not an app specific problem, a lot of users are getting this issue at random, even when using the deafult screensaver provided with Windows. 

Some helpfull articles that I have found:

- https://lifehacker.com/how-to-find-out-what-woke-up-your-computer-last-1550549116 (Check for wake events)
- https://www.makeuseof.com/tag/fix-windows-10-sleep-mode/ (Won't Go To Sleep Section)
- https://appuals.com/windows-10-sleeps-after-1-4-minutes-of-inactivity/ (Reset Power Settings)

**I suggest the Windows Power Settings reset as a last resort option only.**

Furthermore, I have to do a little more research, since I don't remember if Windows 10 (assuming that we have the same version of Windows) supports Sleep Mode while the Screensaver is playing. I am sure this was an option when I still had Windows 7 and 8.1.

The Aerial creator will of course provide some comments, but since managing Sleep Mode and Screensavers is a Windows only task, I don't think third-party screensaver apps have any involvement to do in that. It would also be helpfull if you could test this out with the default Windows Screensavers and come back with some results.

**Comment by FotisSp** [comment]
Hi again,

thanks for the response! Yes my OS is Windows 10. About what i said, when i wrote that my monitor wont go to sleep i meant that it does not turn off after the specified time. Not the whole computer. 

I also followed your advice and tried another built in screen saver so : 

- i set the screen saver to start after 1 minute of inactivity 
- screen to turn of after 5 minutes of inactivity

**Result** was that indeed after 5 minutes the monitor turned off although the screen saver was playing. 

Tried reverting back to aerial screen saver and the monitor did not turn off after the time it was supposed to. 
Clearly something is preventing the monitor from turning off. 

Is there a way to check what is keeping the screen alive ? 

Thanks

**Comment by agilisone** [comment]
Hello,

Perhaps I could shed some light on this issue in hopes that the developers can release a fix for this. 

The reason the display(s) will not go to sleep is because the API responsible for playing the video on the screen is playing it at full screen which is telling the system not to sleep the display(s). This is the same behavior that is replicated when watching a video full screen,

I have the same issue and I'm not sure if I can continue using this version because my displays need to sleep. 

A version of Aerial for Windows, https://github.com/thoemmi/AerialForWindows , has a setting that specifies when the monitors should sleep. I'm not familiar enough with this or that code base to offer solutions on a work around.

For now, the only option is to disable the screen saver when you want your display(s) to sleep.

**Comment by agilisone** [comment]
I do have a workaround that seems to be working for my needs but it involves a free 3rd party application: https://www.redmondpie.com/turn-off-your-notebook-lcd-with-one-click/

I downloaded 1.0.1 (https://www.redmondpie.com/downloadscenter/TurnOffLCDv101.zip) and once it's downloaded, copy the application to a safe place that you can reference later.

Launch Windows Task Scheduler and choose Create New Task:

1. **General** Tab: 
    -  Name and description can be whatever you'd like.
    -  Check off 'Run whether user is logged on or not'
    - Check off 'Do not store password. ...'

2. **Triggers** tab:
    - Click **New** and Choose 'On Idle'

3. **Actions** tab:
    - Click **New** and browse for the 'Turn Off LCD' application.

3. **Conditions** tab:
    - Check off 'Start the task only if the computer is idle for and select the minutes.
    - Wait for Idle: 'Do not wait. 
    -  Make sure all other settings are unchecked.

This will now sleep the displays after the computer is idle for x amount of minutes regardless if the screen saver is running or not.

**Comment by Barleyman** [comment]
> I do have a workaround that seems to be working for my needs but it involves a free 3rd party application: https://www.redmondpie.com/turn-off-your-notebook-lcd-with-one-click/

If you want suspend instead, you could use the official Sysinternals tool to do it. Usage is pretty much the same as you laid out in scheduler. 

https://docs.microsoft.com/en-gb/sysinternals/downloads/psshutdown

**Comment by OrangeJedi** [comment]
The latest version of Aerial now sleeps the computer by default. This should fix any sleep issues that were happening. 

Hopefully there aren't any computers eternally playing Aerial out there 😂
