### ISSUE TITLE
Threat Detection & Quarantined (BitDefender, Windows 10 19041)

### ISSUE THREAD

**Issue by cyberea** [OrangeJedi/Aerial#58]
## Description

BitDefender Total Security neutralized the screensaver file and resulting spawned executable to its quarantine.

![image](https://user-images.githubusercontent.com/4736815/91599908-eff17d80-e95e-11ea-9d51-24d0b2e64f6c.png)

Some searched into Atc4 indicate a false positive, which might be so here but was unsure and so posted this for investigation.

No further triage conducted. Files remain quarantined.

## Reproduction
1. Have BitDefender Total Security installed on OS and updated with the AV module active.
2. Download the screensaver and copy the SCR file to the Windows root.
3. Open screen saver control panel and attempt to select or preview.
4. BDAV should immediately intercept the files.

## Version
v0.5.3

**Comment by VasilisPat** [comment]
As described in this [wiki page](https://github.com/OrangeJedi/Aerial/wiki/FAQ#is-aerialscr-a-malicious-program), it is common for antivirus software to mark .scr files as malicious. Aerial is not designed to harm your pc in any way and is totally safe to use. In order to avoid threat detection for Aerial, from your antivirus software, you can create an exception for it, as shown [here](https://www.bitdefender.com/consumer/support/answer/19797/).
