### ISSUE TITLE
Still being Supported?

### ISSUE THREAD

**Issue by agilisone** [OrangeJedi/Aerial#59]
Just wondering if this version of Aerial for Windows is still being supported. Seems all the other versions so far have gone dormant.

I tried to offer some reasons as to why Issue #51 is occurring. I also feel Aerial for Windows from the following URL could help solve some of the issues being experienced with this version. 

https://github.com/thoemmi/AerialForWindows

For example, that version has a setting that allows the monitors to go to sleep after x amount of time. That would solve the issue with monitors not sleeping. (See issue #51 )

This version,  supports all the videos available from Apple. The above version does not.

There may be other issues that 'theemmi' version can help solve... like video playback issues.

**Comment by OrangeJedi** [comment]
As of right now not much effort is bring put into this version of Aerial. I'm the only developer on the project and don't always have a lot of time to contribute to it. 
I really slowed down my work once #36 became an almost unsolvable problem. When your screensaver can't play correctly for lots of people, it's hard to justify adding new features. On the other hand, I felt like Aerial had gotten to a point where it was very usable and didn't *need* any major fixes. Not that new features won't add to the product, just that until #36 is solved it doesn't make much sense to put in a whole lot of effort. 
Enough small bugs have accumulated over the past few months that I'll probably put out a v0.5.4 sometime in the next few week, depending on how much time I have and how hard the bugs are. I can probably slip a few small features into Aerial at the same time, a sleep after x amount of time should be able to fit in.
After that, I can't promise any updates, other than if new videos come out. If anyone wants to more actively develop Aerial I'll certainly be taking a look at any pull requests and such.

**Comment by agilisone** [comment]
Thank you for your candid and detailed response. I wish I was experienced in ScreenSaver Development for Windows 10. I was a .NET Developer for 9 years but I was on the ASP.NET side. I understand code well but I don't know how this project works together. I honestly wish I could help. So since Aerial for Windows is open source for almost every implementation... it's a shame you can't use the source of others to help some of these issues.

**Comment by OrangeJedi** [comment]
Yeah, this version is written in JavaScript using the Electron framework so I can't really copy code from the other projects because they are mostly written in .NET. It doesn't help the Windows screensavers are not all that common; the documentation isn't great and any code is super old.
Still, it's good to see what features others have added and try to implement them in this version. Opening an issue with the feature request template is a great way to contribute without have to read or write any code.

**Comment by Barleyman** [comment]
I see the sleep option didn't happen in 0.54. Videos are very pretty but the computer will stay up all night showing them unless you manually switch it off so I'll just have to drop Aerial I'm afraid..

**Comment by Barleyman** [comment]
Actually, I wrote a task scheduler script that will make the PC sleep after 30min idle instead. Details in OPs issue.

**Comment by Barleyman** [comment]
@OrangeJedi You say you lost motivation to work on this due to how badly screensavers work.. But we've got a stand-alone screensaver app three quarters of the way already. We can use scheduler to fire up Aerial and it'll play fine. We can use scheduler to boot aerial (taskkill) and switch off screen or sleep computer. What is missing is an installer that would do those steps for us. Possibly also download & extract the sleep tool. Someone pointed out h265-library for you that apparently does 4k as well. 

So.. You might need a bit of glue logic to disable windows screensaver if it's active and check what the display off / sleep values are but that's not a major stretch, you're already installing aerial as a screensaver.

**Comment by OrangeJedi** [comment]
@Barleyman I guess all I had to do was take a break. Hopefully with the changes to how Aerial launches in v1.0.0 #36 can be solved and we can move forward. You were right, we had all the parts, we just needed to re-glue them together. Thank you for believing in Aerial.

I do plan on doing more in the future. See what I said [here](https://github.com/OrangeJedi/Aerial/issues/76#issuecomment-1269230486).
