### ISSUE TITLE
Add an option to retrieve local sunrise/sunset time from online providers

### ISSUE THREAD

**Issue by chiefie** [OrangeJedi/Aerial#61]
As the title suggested.

It would be a nice QoL improvement to have the sunrise/sunset time retrieved from the online providers based on the location reported by the Windows system, or by Lat-Long set manually by the user.

**Comment by MrBigleg** [comment]
What is the current sunrise/sunset time taken from. I'm a new user and have been playing with this setting. Videos don't seem to play as per the setting, I get night videos during the day, so was wondering if I needed to add an offset?

**Comment by VasilisPat** [comment]
I am facing the same issue too. A workaround that seems to be working for me 90% of the time is swapping sunrise and sunset time (ex sunrise 18.00, sunset 07.00).

**Comment by OrangeJedi** [comment]
The sunset/sunrise showing the wrong videos was thankfully discovered and fixed in [v1.0.1](https://github.com/OrangeJedi/Aerial/releases/tag/v1.0.1). And in [v1.1.0](https://github.com/OrangeJedi/Aerial/releases/tag/v1.1.0) the option to determine sunrise/sunset time via latitude/longitude was added. It isn't automatically generated from the user's location, but any good solution for that would require a paid service. So while it isn't off the table, automatically grabbing the location isn't in the near future for Aerial. Still, we have a much better solution than previously.
