### ISSUE TITLE
Doesn't start video screensaver

### ISSUE THREAD

**Issue by purevertigo** [OrangeJedi/Aerial#64]
Running 0.5.4 upgraded from 0.5.3 and when starting the screensaver I only get a white screen.

**Comment by Sarcas666** [comment]
I had the same problem. I completely removed the previous install and reinstalled 0.5.4. That worked.

**Comment by purevertigo** [comment]
How did you completely remove?

**Comment by purevertigo** [comment]
Deleted the directory

**Comment by purevertigo** [comment]
Can someone please help here?

**Comment by Sarcas666** [comment]
> How did you completely remove?

I located the aerial.scr file (look [here](https://www.screensaversplanet.com/help/questions/windows/where-are-screensavers-stored-on-windows-8)) for possible locations) 

I removed the aerial cache folder. For me was that D:\Users\<myusername>\AppData\Local\Aerial

Then I rebooted and then I reinstalled Aerial.

**Comment by purevertigo** [comment]
I still can't get it to work, any ideas @OrangeJedi?

**Comment by Sarcas666** [comment]
I noticed it stopped working for me a well… The screen turns black and only a control-alt-delete gets it unstuck.

**Comment by purevertigo** [comment]
Yes @Sarcas666 mine too.

**Comment by purevertigo** [comment]
Any updates on this @OrangeJedi ?

**Comment by purevertigo** [comment]
update @OrangeJedi ?

**Comment by Barleyman** [comment]
There's actually a manual which nobody will read as it's under "resources\app\documentation" -folder. 

But what you probably want is the cache folder, which is documented here; FAQ also exists!

https://github.com/OrangeJedi/Aerial/wiki/FAQ

Finally, you probably have about a bazillion aerial processes running as they don't terminate when something goes wrong so you may want to take a look in task manager in "details" tab. I had piles of aerial.scr processes there..

**Comment by purevertigo** [comment]
> There's actually a manual which nobody will read as it's under "resources\app\documentation" -folder.
> 
> But what you probably want is the cache folder, which is documented here; FAQ also exists!
> 
> https://github.com/OrangeJedi/Aerial/wiki/FAQ
> 
> Finally, you probably have about a bazillion aerial processes running as they don't terminate when something goes wrong so you may want to take a look in task manager in "details" tab. I had piles of aerial.scr processes there..

tried that. doesn't work sorry

**Comment by Barleyman** [comment]
> tried that. doesn't work sorry

Hey, it worked for me so I'm not sorry ;-) 

What I did was to nuke that folder in roaming and another in local - The old Aerial puts the stuff in local.. Also you'll want to check you don't have aerial.scr in windows folder. And finally try deleting the folder where you put aerial in and extract the zipfile again and "install" it.

**Comment by VasilisPat** [comment]
Found a solution that works for me

- Make sure you start with a fresh version of Aerial (Delete cache location, aerial's settings and the folder of the app)
- Uncheck "Immediately update video cache" option under Settings, Video Cache menu. (Also solution for Issue #74 )
- Create a subfolder inside the folder you have selected as cache location and name it temp. (Also solution for Issue #74 )

This should finaly give a solution for the users that aerial is not starting after installing Beta 0.5.4 version.

**Please provide feedback so I can publish a workaround to the main page of the project**

(Note: @purevertigo  if you find this solution to work please mark the issue as closed, as to reduce the active issues)

**Comment by purevertigo** [comment]
@VasilisPat The settings screen doesn't even open at all.

**Comment by VasilisPat** [comment]
@purevertigo You don't need to open settings screen in order to apply the fix for the version 0.5.4 bugs (afterall the settings page and the screensaver not starting is the actual bug)

In order to make Aerial work again try the following steps:

- Delete the aerial-v0.5.4 folder (the folder which contains the app)
- Delete `C:\Users\%Username%\AppData\Roaming\aerial`
- Delete `C:\Users\%Username%\AppData\Local\aerial` (If not found skip this step only, this folder is a leftover from 0.5.3)
- Perform a restart of your system

To perform the new installation of Aerial:

- Download the 0.5.4 zip
- Install it by right clicking and selecting install to the aerial.scr file
- Open the settings menu **once** and configure your app as desired
- Make sure that "Immediately update video cache" under Settings, Video Cache menu option is **unchecked**
- Close the settings menu and don't start the screensaver

**The following step is the critical one for Aerial to work (Apply before trying to reopen settings menu or start Aerial)**
- Create a subfolder and name it `temp` in your cache location 
  (Default cache loaction is `C:\Users\%Username%\AppData\Roaming\aerial\Cache`)
  (If you have changed the cache location create the `temp` subfolder in the new location)

  The cache folder should look like:
![aerial](https://user-images.githubusercontent.com/65589110/107873810-f5676380-6ebd-11eb-82bb-5c8fef6b5468.JPG)

Now try opening settings and starting the screensaver and it should work correctly!

**Comment by purevertigo** [comment]
thanks, @VasilisPat for that, much appreciated. 
I've decided though to delete the whole thing and not bother anymore. A program this badly/written coded should just be taken over by someone else and fixed anyways.

**Comment by Barleyman** [comment]
You do realize anyone can fork a project in Github? Don't everyone rush in at once now. 

Actually original Aerial is completely comatose. It'd be nice to see proper installer for this one.
