### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by MadNBG** [OrangeJedi/Aerial#8]
Hi, great work so far. Plesse add a video cache. Or, maybe a faster solution: let the user download the video themselves, and if Videos in that dir were found, they are played...

Btw: thanks for developer-options. With that, I found out, that the apple-cert wasnt installed. (Tricky & Strange, because the "old" aeral for win did work - it was able to connect, without that cert).

**Comment by OrangeJedi** [comment]
The video cache is slated for v0.5.0 and mostly coded. You can probably expect a release later this week. I'll close comment and close the issue when I release it. 

Glad to know someone is using the dev options, I build them in for easier testing and figured I'd document. I think the reason why the old Aerial worked without the cert is because Apple used to release the videos on a different (certified) URL, but changed a while ago to a new one. We use the new URL because it has a newer set of videos.

**Comment by MadNBG** [comment]
Great to hear! I hope this will solve that micro stuttering. And the need to be online. :-)

**Comment by OrangeJedi** [comment]
[v0.5.0](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.0-beta) contains a cache! It does need to be enabled though. Let me know if you have issues.
