### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by megaroeny** [OrangeJedi/Aerial#89]
**Describe the bug**
Just installed this, and after initially trying it, it doesn't work anymore for whatever reason. Settings window doesn't show, Preview doesn't show.

Then after trying to delete and restart, it caused my Windows startup to be corrupt, and I had to run a Startup Repair. I'm sure it's not a coincidence. Waited a few minutes later after fixing my startup, and then "aerial" disappeared from the Screen Saver options. 🤔 

Windows won't let me delete the extracted folder now either, since it says it's "In use."

Beware installing this now with the latest version of Win 10.

**To Reproduce**
1. Download 0.5.4
2. Move extracted folder to desired location (I moved mine to another drive if that's an issue.)
3. Right-click scr file and install
4. Go to screen saver settings in Windows, and try to open Settings or Preview
5. Nothing appears

**Aerial Version**
0.5.4

**Additional context**
Edition	Windows 10 Home
Version	21H1
Installed on	‎2/‎1/‎2021
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.

**Comment by CommieColin** [comment]
Have you changed your cache directory, by chance? If so, please create a folder called "temp" within that cache directory and see if this resolves your issue.

**Comment by megaroeny** [comment]
> Have you changed your cache directory, by chance? If so, please create a folder called "temp" within that cache directory and see if this resolves your issue.

Cache directory for what? Sorry don't follow. Windows or the screensaver? 

I can't change it for the screensaver since it won't even launch properly, if that's what you mean.

**Comment by CommieColin** [comment]
The cache directory for the screensaver itself - if there is not a temp folder in the location, it will cause the screensaver to crash and you won't be able to open the settings to change the location of the cache. You can start fresh by deleting the aerial folder located at C:\Users\username\AppData\Roaming\aerial

Try deleting that and then launch the screensaver settings again, if you haven't already.

**Comment by megaroeny** [comment]
> You can start fresh by deleting the aerial folder located at C:\Users\username\AppData\Roaming\aerial
> 
> Try deleting that and then launch the screensaver settings again, if you haven't already.

Okay and this is after installing the screensaver with the .scr file?

**Comment by CommieColin** [comment]
Correct - if something was corrupted or otherwise went wrong and it's preventing you from opening the screensaver at all, this *should* allow you to start fresh with default settings. 

I'm not sure if at some point you directed the screensaver to try and store its video cache somewhere other than the default location, but in my experience this will at least allow you to re-launch the screensaver with default settings. 

My recommendation would be to install the screensaver itself from your main drive - I have my in C:\Windows\aerial-v0.5.4\
I installed normally, by right clicking the .scr file and clicking Install - I only mention this because you mentioned having it installed on another drive. My issue had to do with the screensaver trying to cache videos to a location without a temp folder, which causes the entire thing to crash and leaves you unable to even open settings, which is why I'm suggesting these steps. 

if this isn't related to your issue then my apologies - trash or treasure, as they say. I hope it works for you.

**Comment by benalt613** [comment]
I had Aerial installed from elsewhere and came across this version so renamed it aerial2 and installed and immediately had the same issue. Not sure if it is because I had another version installed from elsewhere.

**Comment by OrangeJedi** [comment]
Updated to v1.0.0 should solve this error as it completely changes how Aerial is installed. If you are still having issues after updating please open a new issue.
