### ISSUE TITLE
Any plan to dynamically fetch / add screensavers from newer versions of tvOS?

### ISSUE THREAD

**Issue by OscBacon** [OrangeJedi/Aerial#91]
Hi,
It doesn't seem that Aerial currently fetches new screensaver videos, such as those in tvOS 15.
It would be nice to at least have a manual option to fetch newer screensaver videos

**Comment by OscBacon** [comment]
Looking at https://github.com/OrangeJedi/Aerial/blob/cfe17c520491b9eb9b6dda520eb426a716ef109d/app.js#L237,
it seems like this could be implemented by having an  "update videos list" button, and an ipcMain.on() event handler, that would fetch the latest videos list.
It seems from https://sylvan.apple.com/Aerials/resources-15.tar that the tvOS 15 json file has a slightly modified format.
While the Aerial could be rewritten to handle the new format, it would also work to just fetch the latets json file, and convert the contents of each entry to the previous format.

I am a bit busy now, but I'd be happy to help look into this when my winter break happens!

**Comment by SquaredCircle84** [comment]
> Looking at
> 
> https://github.com/OrangeJedi/Aerial/blob/cfe17c520491b9eb9b6dda520eb426a716ef109d/app.js#L237
> ,
> it seems like this could be implemented by having an "update videos list" button, and an ipcMain.on() event handler, that would fetch the latest videos list.
> It seems from https://sylvan.apple.com/Aerials/resources-15.tar that the tvOS 15 json file has a slightly modified format.
> While the Aerial could be rewritten to handle the new format, it would also work to just fetch the latets json file, and convert the contents of each entry to the previous format.
> 
> I am a bit busy now, but I'd be happy to help look into this when my winter break happens!

I have absolutely no idea how any of this works, but, for what it's worth, I'm excited as the possibility of you continuing this project.  Thanks.

**Comment by TheFreshPrins** [comment]
> Looking at
> 
> https://github.com/OrangeJedi/Aerial/blob/cfe17c520491b9eb9b6dda520eb426a716ef109d/app.js#L237
> 
> ,
> it seems like this could be implemented by having an "update videos list" button, and an ipcMain.on() event handler, that would fetch the latest videos list.
> It seems from https://sylvan.apple.com/Aerials/resources-15.tar that the tvOS 15 json file has a slightly modified format.
> While the Aerial could be rewritten to handle the new format, it would also work to just fetch the latets json file, and convert the contents of each entry to the previous format.
> I am a bit busy now, but I'd be happy to help look into this when my winter break happens!

That would be super awesome if you could make that happen. I have Aerial running for several years now but getting a bit bored with the always same video's.

Tried to import all the community based video's together with the tvOS 15 video's from Aerial for Mac, but seems like the ''custom video'' function in Aerial for windows doesn't work. Maybe because those video's have a HEVC/MOV format?

**Comment by zoxim** [comment]
I was able to add the newer videos by downloading them from https://docs.google.com/spreadsheets/d/1bboTohF06r-fafrImTExAPqM9m6h2m2lgJyAkQuYVJI/edit#gid=1684411812  (Apple TV Aerial Screen Saver Links- Updated January 2022)
and then converting them via VLC (convert: Video for MPEG4 1080p TV/device in dropdown menu). The files then show up in the custom video function in Aerial and can be added. Some really nice ones, especially the Iceland ones.

**Comment by TheFreshPrins** [comment]
> I was able to add the newer videos by downloading them from https://docs.google.com/spreadsheets/d/1bboTohF06r-fafrImTExAPqM9m6h2m2lgJyAkQuYVJI/edit#gid=1684411812 (Apple TV Aerial Screen Saver Links- Updated January 2022) and then converting them via VLC (convert: Video for MPEG4 1080p TV/device in dropdown menu). The files then show up in the custom video function in Aerial and can be added. Some really nice ones, especially the Iceland ones.

Thanks Zoxim! I was able to download & convert them all via VLC! Only thing now is that I receive a Javascript error when the custom video begins to play. Did you also made a ''temp'' folder in the custom video folder?

Thanks in advance! :)

**Comment by SquaredCircle84** [comment]
> I was able to add the newer videos by downloading them from https://docs.google.com/spreadsheets/d/1bboTohF06r-fafrImTExAPqM9m6h2m2lgJyAkQuYVJI/edit#gid=1684411812 (Apple TV Aerial Screen Saver Links- Updated January 2022) and then converting them via VLC (convert: Video for MPEG4 1080p TV/device in dropdown menu). The files then show up in the custom video function in Aerial and can be added. Some really nice ones, especially the Iceland ones.

This is great!  The only concern I have is that I get a security risk warning when trying to download.  Why is that coming up?

**Comment by OrangeJedi** [comment]
Aerial v1.0.0 has the new videos in it!

I'll also try to answer a few if the other questions that were brought up.

- If you keep having issues with custom videos open another issue fit them. Because of technology limits Aerial can't play h.265 videos so makes sure you download the h.264 ones or convert them.
- The security notice pops up on Apple's videos sometime is because Apple selfsigns some of the urls. It's fine to ignore it.
- Currently there isn't any plan to automatically update the videos because of how the .tar format works. The URL changes for every release (and sometimes the format), you would have to unpack the .tar file, and the strings with the description text are very messy to import. For now having someone manually update the video list is what will work best. I am looking for other solutions though.
